services:
  vm-manager:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - anyrun-network
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    ports:
      - "6080:6080"
      - "5901-5921:5901-5921"
    environment:
      - MAX_VMS_PER_USER=3
      - VM_BASE_PORT=6080
      - NOVNC_PORT_RANGE=6080-6100
      - VNC_PORT_RANGE=5901-5921

networks:
  anyrun-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
    driver_opts:
      com.docker.network.bridge.name: br-anyrun
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"